version: "3.5"
services:
  p071-zabbix-server-mysql:
    environment:
      - DB_SERVER_HOST=10.62.229.162
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=${MYSQL_USER_PASS}
      - ZBX_STARTPOLLERS=5
      - ZBX_IPMIPOLLERS=0
      - ZBX_STARTPOLLERSUNREACHABLE=5
      - ZBX_STARTPINGERS=0
      - ZBX_STARTDISCOVERERS=0
      - ZBX_STARTHTTPPOLLERS=0
      - ZBX_STARTJAVAPOLLERS=0
      - ZBX_STARTVMWARECOLLECTORS=0
      - ZBX_ENABLE_SNMP_TRAPS=false
      - ZBX_CACHESIZE=32M
      - ZBX_VALUECACHESIZE=512M
      - ZBX_PROXYCONFIGFREQUENCY=300
      - ZBX_STARTPROXYPOLLERS=3
    container_name: p071-zabbix-server-mysql
    image: docker.io/zabbix/zabbix-server-mysql:centos-5.0.2
#    network_mode: host
    ports:
      - "10051:10051"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    extra_hosts:
      - "sys.local:192.168.226.60"

  p071-zabbix-web-nginx:
    environment:
      - DB_SERVER_HOST=10.62.229.162
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=${MYSQL_USER_PASS}
#Jlsdfmewr9Ndlrjw3mJvbioP#
      - ZBX_SERVER_HOST=10.62.229.162
      - PHP_TZ=Europe/Moscow
      - ZBX_SERVER_NAME=TNOP02
    container_name: p071-zabbix-web-nginx
    image:  docker.io/zabbix/zabbix-web-nginx-mysql:centos-5.0.2
    ports:
      - 81:8080
#    network_mode: host
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    extra_hosts:
      - "sys.local:192.168.226.60"

  db80:
    image:  docker.io/mysql:8.0
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    restart: on-failure
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password  --skip-name-resolve=ON  --skip-mysqlx
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_RANDOM_ROOT_PASSWORD=0
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=zabbix
      - MYSQL_HOST="0.0.0.0"
      - MYSQL_TCP_PORT=3306
      - MYSQLX_TCP_PORT=33060
      - TZ=MSK
    ports:
      - "3306:3306"
      - "33068:33068"
      - "33060:33060"
    volumes:
      - /data/mysql:/var/lib/mysql:rw
      - ./mysql:/etc/mysql/conf.d:ro
#    secrets:
#      - MYSQL_USER
#      - MYSQL_PASSWORD
#      - MYSQL_ROOT_PASSWORD
#    networks:
#      - mysql-net
#    network_mode: host
#опция мапит все порты на локальный хост, менять порт mysql на незанятый    
    privileged: true
    userns_mode: 'host'

#secrets:
#  MYSQL_USER:
#    file: ./.MYSQL_USER:z
#  MYSQL_USER_PASSWORD:
#    file: ./.MYSQL_PASSWORD:z
#  MYSQL_ROOT_PASSWORD:
#    file: ./.MYSQL_ROOT_PASSWORD:z

